function library = import_file(workbookFile, sheetName, dataLines)
%IMPORT_FILE Import data from a spreadsheet
%  LIBRARY = IMPORT_FILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  LIBRARY = IMPORT_FILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  LIBRARY = IMPORT_FILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  library = import_file("librarything.xls", "Simple", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Dec-2024 16:24:14

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 34);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Title", "Var3", "PrimaryAuthor", "Var5", "Var6", "Var7", "Var8", "Date", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "LCClassification", "ISBN"];
opts.SelectedVariableNames = ["Title", "PrimaryAuthor", "Date", "LCClassification", "ISBN"];
opts.VariableTypes = ["char", "string", "char", "string", "char", "char", "char", "char", "double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Title", "Var3", "PrimaryAuthor", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "LCClassification", "ISBN"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Title", "Var3", "PrimaryAuthor", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "LCClassification", "ISBN"], "EmptyFieldRule", "auto");

% Import the data
library = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    library = [library; tb]; %#ok<AGROW>
end

end